In [1]:
import pandas as pd

In [2]:
# read csv file
df = pd.read_csv(r"C:\Users\krishna rawal\OneDrive\Desktop\players_20.csv")
# set index
df.set_index('short_name', inplace = True)  
# Select column
df= df[['long_name','age','dob','height_cm','weight_kg','nationality','club']]

In [3]:
# show data frame
df

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

# 1 Sample()

In [14]:
# extract 10 random elements from the "nationality" column
df['nationality'].sample(10 ,  random_state=99)

short_name
R. Alvarado               Mexico
Qiao Wei                China PR
E. Paredes                 Chile
K. Stoyanov             Bulgaria
M. Chudý                Slovakia
D. Sundaram                India
R. Gagliardini             Italy
G. Debeljuh              Croatia
Kim Seung Yong    Korea Republic
M. Hansen                Denmark
Name: nationality, dtype: object

In [16]:
#extract a random 20% sample of the dataframe
df.sample(frac=0.2 , random_state=12)

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
Y. Thoelen,Yannick Thoelen,28,1990-07-18,188,89,Belgium,KV Mechelen
M. Nadé,Mickaël Nadé,20,1999-03-04,188,80,France,AS Saint-Étienne
V. García,Víctor Hugo García Hernández,25,1994-06-11,178,71,Venezuela,Vitória Guimarães
M. Gyamfi,Maxwell Gyamfi,19,2000-01-18,185,75,Germany,VfL Bochum 1848
W. Cyprien,Wylan Cyprien,24,1995-01-28,180,75,France,OGC Nice
...,...,...,...,...,...,...,...
H. Kadish,Hassan Kadish,26,1992-09-26,179,73,Saudi Arabia,Al Hilal
A. Chapman,Aaron Chapman,29,1990-05-29,203,92,England,Peterborough United
I. Ezekiel,Imoh Ezekiel,25,1993-10-24,178,70,Nigeria,KV Kortrijk
H. Sakai,酒井 宏樹,29,1990-04-12,183,70,Japan,Olympique de Marseille
C. Keșerü,Claudiu Andrei Keșerü,32,1986-12-02,178,71,Romania,Romania

In [17]:
# unsample: increase the sampling rate -> frac >1 (Note : replace parameter has to be True for frac parameter > 1 )
df.sample(frac = 2 , replace=True )

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
K. Kennedy,Kieran Kennedy,25,1993-09-23,183,70,England,Port Vale
V. Rongier,Valentin Rongier,24,1994-12-07,172,70,France,FC Nantes
A. Di María,Ángel Fabián Di María Hernández,31,1988-02-14,180,69,Argentina,Paris Saint-Germain
A. Al Riou,Abdulrahman Khalid Al Rio,25,1994-05-15,189,70,Saudi Arabia,Al Wehda
M. Senesi,Marcos Senesi,22,1997-05-10,183,80,Argentina,San Lorenzo de Almagro
...,...,...,...,...,...,...,...
C. Larin,Cyle Larin,24,1995-04-17,187,92,Canada,SV Zulte-Waregem
O. Abildgaard,Oliver Abildgaard,23,1996-06-10,192,86,Denmark,Aalborg BK
A. Attiah,Abdulquddus Attiah,22,1997-03-01,190,77,Saudi Arabia,Al Wehda
S. Glarner,Stefan Glarner,31,1987-11-21,177,74,Switzerland,FC Thun
S. Knežević,Stefan Knežević,22,1996-10-30,187,81,Switzerland,FC Luzern