In [2]:
import pandas as pd

In [3]:
# reading the csv file
df_exams = pd.read_csv(r"C:\Users\krishna rawal\dataset.csv")
df_exams.head()

,hospital_name,gender,color,job_title,ssn,birthdate,city,country,phone_number,email
0,WAGONER HOSPITAL AUTHORITY,Female,Maroon,Social Worker,414-96-9723,9/23/1980,Fraile Pintado,Argentina,644-374-7372,gchansonnau0@live.com
1,ATHOL MEMORIAL HOSPITAL INCORPORATED,Female,Orange,Social Worker,158-68-8337,8/31/1954,Taxisco,Guatemala,487-683-5255,cwinckworth1@about.com
2,MCLEOD REGIONAL MEDICAL CENTER OF PEE DEE INC,Male,Khaki,Quality Engineer,656-97-2511,3/16/1973,Sakai,Japan,255-989-3989,hsollars2@google.com
3,SUTTER VALLEY HOSPITALS,Male,Maroon,Web Developer I,598-01-7806,5/14/1974,Кондово,Macedonia,650-792-4085,ahallward3@theguardian.com
4,NORTH SUNFLOWER MEDICAL CENTER,Male,Pink,Senior Sales Associate,776-58-1786,12/30/1962,Bāfq,Iran,110-479-5503,vkirke4@joomla.org

# 1 Create Index

In [4]:
import numpy as np
import random

In [5]:
# Creating non repetitive values for the index
new_index=np.arange(0,1000)

In [6]:
# Shuffling the indexes
random.shuffle(new_index)

In [7]:
new_index

array([133, 789, 832, 212, 431, 142, 635, 239, 992, 400, 195, 545,  91,
       703, 190, 490, 136, 932, 616, 343, 170, 882, 345, 785, 684,   0,
       637, 379,  56, 297, 415, 541, 549, 396, 815, 951, 769,  39, 853,
       470, 226, 628, 161,  28, 120, 965, 247, 456,  25,  82,  98,  97,
       145, 899, 649, 517, 937, 502,  15, 694, 457, 987, 203, 255, 565,
       973,  84, 700, 927, 786,  13, 745, 516, 662, 139, 535, 140, 842,
       176, 394, 277,  62, 876, 509, 960, 339, 437,  26, 526, 480, 352,
       197, 511, 492, 846,   4, 484, 744,  88, 935,  23, 606, 525, 979,
       831, 722, 715, 209, 762,  70,  64,   7, 625, 575, 829, 392, 622,
       636, 187, 282, 276, 962,  80, 178, 211, 843, 862, 584, 131, 812,
       320,  69, 374, 196, 793, 825, 617,  53,  60, 795, 486, 587, 407,
       356, 563, 579, 467, 914, 824, 108, 402, 461, 409, 496, 966, 747,
       774, 675, 975, 519, 898, 561, 597, 601, 816, 642, 726, 123, 459,
       764, 103, 271, 670, 650, 736, 520, 577, 423, 943, 743, 644, 364,
       838, 510, 300, 118, 906, 860, 296, 766,  45,  71, 488, 603, 673,
       928, 548, 453, 640, 833, 907, 435, 389, 692, 682, 100, 316, 369,
       648, 856, 523,  30, 848, 329, 540, 678, 952, 820, 558, 727, 836,
       524, 383, 543,  33, 538, 167, 482, 172, 559, 312, 799, 671, 991,
        83, 834, 333, 913, 660, 657, 193, 290, 936, 432, 242, 441, 593,
       507, 498, 311, 489, 701,  24, 199, 879, 355, 719, 275, 613, 806,
       214, 107, 359, 646, 254, 551, 416, 802, 630, 420, 292, 651, 436,
       761, 232, 925, 330, 357, 553, 445, 732, 869, 964, 778,  22, 594,
       615, 425, 809,  10, 566, 681, 569, 465, 508, 129, 916,  58, 245,
       883, 169, 805, 529, 493, 668, 717, 184, 677, 915, 375, 325, 665,
       658, 542, 257, 250, 417, 210, 518, 349, 887, 521,  44,  85, 377,
       532, 294, 147,  89, 236, 822, 146, 249, 306, 830,  72, 162,   1,
       865, 514, 159, 223, 135, 968, 224, 160, 326, 980, 810, 168, 411,
       655, 381, 243, 909, 547, 299, 835,   9, 990, 335, 626, 851, 191,
       716, 152, 611, 443, 234,  43, 505, 346, 385, 750, 460, 653, 376,
       500, 248, 718, 710,  93, 477, 373, 413, 903, 892, 279, 241, 156,
       895, 974, 235, 922, 262, 360, 365, 823, 784,  55, 408, 556, 590,
       993, 469, 910, 672, 958, 800,  65, 728,  11, 171, 476, 627, 751,
       741, 428, 779, 268, 370,  47, 384, 947, 861, 205,   5, 720, 332,
       605, 266, 506, 685, 749, 780, 499, 667,  19, 697, 849, 259,  35,
       752, 919, 759, 967, 527, 798, 229, 688, 837, 336, 106, 902, 380,
       265, 334, 331, 621, 150, 612, 724, 288, 143, 399, 608, 122, 403,
       372, 576, 748, 873,  79, 610, 483, 571, 699, 466, 434, 342, 961,
       183, 144, 712, 323, 713, 206, 963, 455, 412, 781,  81, 278, 572,
       641, 324, 844, 938, 230, 945, 189,   2, 868, 740, 705, 281, 344,
        31, 285, 693, 924, 953, 544, 896, 148, 303, 647, 969, 273, 341,
       138, 981, 272, 128, 391, 252, 310, 801,  16, 905,  75, 926, 382,
       976, 388, 227, 157, 481,  74, 215, 102, 293, 591, 803, 185, 773,
       218, 871, 462, 137, 897, 458, 674, 348, 904, 607, 528, 760, 497,
       826,  66, 404, 440, 711, 378, 350, 353, 244, 270, 763, 126, 609,
       600, 996, 845, 709,  50, 319, 946, 813, 994, 797, 450, 634, 819,
       314, 811, 472, 194, 847, 664, 536, 588, 253, 351,  92, 920, 231,
       742, 531, 114, 661, 918,  94, 121, 775, 923, 930, 934,  38, 401,
       734, 730, 222, 177, 573, 704, 220, 911, 984, 698, 771,  52, 530,
       554, 430, 537, 955, 950, 631, 686, 438, 659,  96, 683,  46, 309,
       948, 723, 585, 328, 598, 125, 739, 746,  90, 451, 983, 970, 539,
       202, 894, 840, 264, 386, 117, 777, 917, 989, 246, 782, 765, 645,
       228, 534, 624,  21, 555, 821, 358,  68,  14, 959, 471, 901,  78,
       988, 870, 872, 110, 941, 390, 119, 854, 267, 479, 614, 367, 933,
       552, 442, 269, 473, 687, 620, 706, 592, 165, 307, 768, 707, 859,
       454, 371, 337, 581,  40, 900, 596, 583, 695, 240, 618, 149, 180,
       889,  57,  20,  34, 501, 632, 881, 127, 515,  49, 347, 995, 689,
       929, 208, 574, 912, 182, 863, 783, 599, 302, 954, 164, 233, 263,
       550, 985, 452, 340, 669, 794, 283, 908, 173, 166, 652, 827, 731,
        27, 422, 421, 589, 818, 956, 738, 808, 109, 286, 321, 885, 560,
       414, 623, 313, 513, 485, 857,  37,  77, 942, 188, 944, 512, 852,
       957, 533, 814, 295, 998, 817, 504, 429, 405, 867, 972, 880, 877,
       568, 305, 158, 753, 393, 153, 289, 940, 733, 256, 424, 874, 567,
       595, 251, 564, 891, 570, 666, 464, 586, 737, 322, 633, 410, 361,
       977, 757, 354,  86, 619, 841, 582, 772, 198, 796,  29, 602, 217,
       104, 315, 790, 363, 318, 866,  61, 338, 639, 426, 487, 756, 494,
       971, 200, 284, 463, 130, 258, 643,  59, 807, 260, 696, 207, 562,
       978, 754, 893,  54, 225, 654, 776, 767, 447,  36, 291, 397, 444,
       181, 708, 192, 213,  18, 546, 949, 886, 890, 395, 663, 111, 931,
       261, 878, 580,  17, 439, 327, 787, 419, 204, 888, 557, 237, 308,
       368, 690,   8,  67, 134, 478, 201, 427, 304, 298, 449, 406,   3,
       366,  73, 491,  41, 875, 115, 788, 680, 238, 997, 448, 758, 174,
       175,  87, 155, 755, 101, 503,  42, 629, 398, 280, 151, 474, 792,
       656, 362, 839, 999, 475, 216, 791, 982, 691, 154,   6, 317, 679,
       702, 638,  76, 112, 301, 418, 604, 495, 770, 858, 113, 578, 986,
       676, 804, 132, 274, 921, 939, 105, 387,  99, 828, 116, 884, 735,
        48,  95, 855, 163,  32,  12, 468, 433, 850, 446, 721, 725, 864,
        51, 219, 221, 141, 714, 522, 729, 287, 179,  63, 124, 186])

In [8]:
# Create a new column with new index
df_exams['new_index'] = new_index
df_exams

,hospital_name,gender,color,job_title,ssn,birthdate,city,country,phone_number,email,new_index
0,WAGONER HOSPITAL AUTHORITY,Female,Maroon,Social Worker,414-96-9723,9/23/1980,Fraile Pintado,Argentina,644-374-7372,gchansonnau0@live.com,133
1,ATHOL MEMORIAL HOSPITAL INCORPORATED,Female,Orange,Social Worker,158-68-8337,8/31/1954,Taxisco,Guatemala,487-683-5255,cwinckworth1@about.com,789
2,MCLEOD REGIONAL MEDICAL CENTER OF PEE DEE INC,Male,Khaki,Quality Engineer,656-97-2511,3/16/1973,Sakai,Japan,255-989-3989,hsollars2@google.com,832
3,SUTTER VALLEY HOSPITALS,Male,Maroon,Web Developer I,598-01-7806,5/14/1974,Кондово,Macedonia,650-792-4085,ahallward3@theguardian.com,212
4,NORTH SUNFLOWER MEDICAL CENTER,Male,Pink,Senior Sales Associate,776-58-1786,12/30/1962,Bāfq,Iran,110-479-5503,vkirke4@joomla.org,431
...,...,...,...,...,...,...,...,...,...,...,...
995,"PROMISE HOSPITAL OF ASCENSION, INC.",Female,Teal,Database Administrator III,721-46-0324,5/6/1988,Mantes-la-Jolie,France,871-485-7072,tfaldoern@unesco.org,287
996,THE CAMBRIDGE HOSPITAL,Female,Indigo,Executive Secretary,735-52-4327,4/2/1984,Peicheng,China,824-715-0847,aridgerro@prlog.org,179
997,EAST ORANGE GENERAL HOSPITAL,Male,Orange,Geological Engineer,885-37-7943,11/20/1957,Askainen,Finland,358-151-6573,mlarozerp@hostgator.com,63
998,SALEM MEMORIAL HOSPITAL,Female,Maroon,Electrical Engineer,157-51-4509,2/29/1996,Līkak,Iran,466-151-5908,nluffmanrq@cargocollective.com,124
999,MARY IMOGENE BASSETT HOSPITAL,Male,Red,Human Resources Assistant II,880-41-9582,11/16/1953,Niverville,Canada,920-360-2577,mmcgloinrr@ycombinator.com,186

# 2.Set Index

In [9]:
 # set new_index column as index
df_exams.set_index('new_index')

,hospital_name,gender,color,job_title,ssn,birthdate,city,country,phone_number,email
new_index,,,,,,,,,,
133,WAGONER HOSPITAL AUTHORITY,Female,Maroon,Social Worker,414-96-9723,9/23/1980,Fraile Pintado,Argentina,644-374-7372,gchansonnau0@live.com
789,ATHOL MEMORIAL HOSPITAL INCORPORATED,Female,Orange,Social Worker,158-68-8337,8/31/1954,Taxisco,Guatemala,487-683-5255,cwinckworth1@about.com
832,MCLEOD REGIONAL MEDICAL CENTER OF PEE DEE INC,Male,Khaki,Quality Engineer,656-97-2511,3/16/1973,Sakai,Japan,255-989-3989,hsollars2@google.com
212,SUTTER VALLEY HOSPITALS,Male,Maroon,Web Developer I,598-01-7806,5/14/1974,Кондово,Macedonia,650-792-4085,ahallward3@theguardian.com
431,NORTH SUNFLOWER MEDICAL CENTER,Male,Pink,Senior Sales Associate,776-58-1786,12/30/1962,Bāfq,Iran,110-479-5503,vkirke4@joomla.org
...,...,...,...,...,...,...,...,...,...,...
287,"PROMISE HOSPITAL OF ASCENSION, INC.",Female,Teal,Database Administrator III,721-46-0324,5/6/1988,Mantes-la-Jolie,France,871-485-7072,tfaldoern@unesco.org
179,THE CAMBRIDGE HOSPITAL,Female,Indigo,Executive Secretary,735-52-4327,4/2/1984,Peicheng,China,824-715-0847,aridgerro@prlog.org
63,EAST ORANGE GENERAL HOSPITAL,Male,Orange,Geological Engineer,885-37-7943,11/20/1957,Askainen,Finland,358-151-6573,mlarozerp@hostgator.com
124,SALEM MEMORIAL HOSPITAL,Female,Maroon,Electrical Engineer,157-51-4509,2/29/1996,Līkak,Iran,466-151-5908,nluffmanrq@cargocollective.com
186,MARY IMOGENE BASSETT HOSPITAL,Male,Red,Human Resources Assistant II,880-41-9582,11/16/1953,Niverville,Canada,920-360-2577,mmcgloinrr@ycombinator.com

# 3. Sort Index

In [11]:
# Sort Datframe by new index
df_exams.sort_index(ascending=False ,inplace = True )
df_exams

,hospital_name,gender,color,job_title,ssn,birthdate,city,country,phone_number,email,new_index
999,MARY IMOGENE BASSETT HOSPITAL,Male,Red,Human Resources Assistant II,880-41-9582,11/16/1953,Niverville,Canada,920-360-2577,mmcgloinrr@ycombinator.com,186
998,SALEM MEMORIAL HOSPITAL,Female,Maroon,Electrical Engineer,157-51-4509,2/29/1996,Līkak,Iran,466-151-5908,nluffmanrq@cargocollective.com,124
997,EAST ORANGE GENERAL HOSPITAL,Male,Orange,Geological Engineer,885-37-7943,11/20/1957,Askainen,Finland,358-151-6573,mlarozerp@hostgator.com,63
996,THE CAMBRIDGE HOSPITAL,Female,Indigo,Executive Secretary,735-52-4327,4/2/1984,Peicheng,China,824-715-0847,aridgerro@prlog.org,179
995,"PROMISE HOSPITAL OF ASCENSION, INC.",Female,Teal,Database Administrator III,721-46-0324,5/6/1988,Mantes-la-Jolie,France,871-485-7072,tfaldoern@unesco.org,287
...,...,...,...,...,...,...,...,...,...,...,...
4,NORTH SUNFLOWER MEDICAL CENTER,Male,Pink,Senior Sales Associate,776-58-1786,12/30/1962,Bāfq,Iran,110-479-5503,vkirke4@joomla.org,431
3,SUTTER VALLEY HOSPITALS,Male,Maroon,Web Developer I,598-01-7806,5/14/1974,Кондово,Macedonia,650-792-4085,ahallward3@theguardian.com,212
2,MCLEOD REGIONAL MEDICAL CENTER OF PEE DEE INC,Male,Khaki,Quality Engineer,656-97-2511,3/16/1973,Sakai,Japan,255-989-3989,hsollars2@google.com,832
1,ATHOL MEMORIAL HOSPITAL INCORPORATED,Female,Orange,Social Worker,158-68-8337,8/31/1954,Taxisco,Guatemala,487-683-5255,cwinckworth1@about.com,789
0,WAGONER HOSPITAL AUTHORITY,Female,Maroon,Social Worker,414-96-9723,9/23/1980,Fraile Pintado,Argentina,644-374-7372,gchansonnau0@live.com,133