In [1]:
import pandas as pd

In [7]:
# reading the csv file
df_exams = pd.read_csv(r"C:\Users\krishna rawal\dataset.csv")

In [8]:
df_exams

,hospital_name,gender,color,job_title,ssn,birthdate,city,country,phone_number,email
0,WAGONER HOSPITAL AUTHORITY,Female,Maroon,Social Worker,414-96-9723,9/23/1980,Fraile Pintado,Argentina,644-374-7372,gchansonnau0@live.com
1,ATHOL MEMORIAL HOSPITAL INCORPORATED,Female,Orange,Social Worker,158-68-8337,8/31/1954,Taxisco,Guatemala,487-683-5255,cwinckworth1@about.com
2,MCLEOD REGIONAL MEDICAL CENTER OF PEE DEE INC,Male,Khaki,Quality Engineer,656-97-2511,3/16/1973,Sakai,Japan,255-989-3989,hsollars2@google.com
3,SUTTER VALLEY HOSPITALS,Male,Maroon,Web Developer I,598-01-7806,5/14/1974,Кондово,Macedonia,650-792-4085,ahallward3@theguardian.com
4,NORTH SUNFLOWER MEDICAL CENTER,Male,Pink,Senior Sales Associate,776-58-1786,12/30/1962,Bāfq,Iran,110-479-5503,vkirke4@joomla.org
...,...,...,...,...,...,...,...,...,...,...
995,"PROMISE HOSPITAL OF ASCENSION, INC.",Female,Teal,Database Administrator III,721-46-0324,5/6/1988,Mantes-la-Jolie,France,871-485-7072,tfaldoern@unesco.org
996,THE CAMBRIDGE HOSPITAL,Female,Indigo,Executive Secretary,735-52-4327,4/2/1984,Peicheng,China,824-715-0847,aridgerro@prlog.org
997,EAST ORANGE GENERAL HOSPITAL,Male,Orange,Geological Engineer,885-37-7943,11/20/1957,Askainen,Finland,358-151-6573,mlarozerp@hostgator.com
998,SALEM MEMORIAL HOSPITAL,Female,Maroon,Electrical Engineer,157-51-4509,2/29/1996,Līkak,Iran,466-151-5908,nluffmanrq@cargocollective.com
999,MARY IMOGENE BASSETT HOSPITAL,Male,Red,Human Resources Assistant II,880-41-9582,11/16/1953,Niverville,Canada,920-360-2577,mmcgloinrr@ycombinator.com

In [9]:
#show first 5 rows in a dataframe
df_exams.head()

,hospital_name,gender,color,job_title,ssn,birthdate,city,country,phone_number,email
0,WAGONER HOSPITAL AUTHORITY,Female,Maroon,Social Worker,414-96-9723,9/23/1980,Fraile Pintado,Argentina,644-374-7372,gchansonnau0@live.com
1,ATHOL MEMORIAL HOSPITAL INCORPORATED,Female,Orange,Social Worker,158-68-8337,8/31/1954,Taxisco,Guatemala,487-683-5255,cwinckworth1@about.com
2,MCLEOD REGIONAL MEDICAL CENTER OF PEE DEE INC,Male,Khaki,Quality Engineer,656-97-2511,3/16/1973,Sakai,Japan,255-989-3989,hsollars2@google.com
3,SUTTER VALLEY HOSPITALS,Male,Maroon,Web Developer I,598-01-7806,5/14/1974,Кондово,Macedonia,650-792-4085,ahallward3@theguardian.com
4,NORTH SUNFLOWER MEDICAL CENTER,Male,Pink,Senior Sales Associate,776-58-1786,12/30/1962,Bāfq,Iran,110-479-5503,vkirke4@joomla.org

In [10]:
# show last 5 rows in a dataframe
df_exams.tail()

,hospital_name,gender,color,job_title,ssn,birthdate,city,country,phone_number,email
995,"PROMISE HOSPITAL OF ASCENSION, INC.",Female,Teal,Database Administrator III,721-46-0324,5/6/1988,Mantes-la-Jolie,France,871-485-7072,tfaldoern@unesco.org
996,THE CAMBRIDGE HOSPITAL,Female,Indigo,Executive Secretary,735-52-4327,4/2/1984,Peicheng,China,824-715-0847,aridgerro@prlog.org
997,EAST ORANGE GENERAL HOSPITAL,Male,Orange,Geological Engineer,885-37-7943,11/20/1957,Askainen,Finland,358-151-6573,mlarozerp@hostgator.com
998,SALEM MEMORIAL HOSPITAL,Female,Maroon,Electrical Engineer,157-51-4509,2/29/1996,Līkak,Iran,466-151-5908,nluffmanrq@cargocollective.com
999,MARY IMOGENE BASSETT HOSPITAL,Male,Red,Human Resources Assistant II,880-41-9582,11/16/1953,Niverville,Canada,920-360-2577,mmcgloinrr@ycombinator.com

In [11]:
# show last n rows in a dataframe
df_exams.tail(10)

,hospital_name,gender,color,job_title,ssn,birthdate,city,country,phone_number,email
990,NEWARK-WAYNE COMMUNITY HOSPITAL,Female,Aquamarine,Assistant Media Planner,128-66-3918,10/17/1996,Vidyayevo,Russia,152-200-6736,kgaudinri@wikipedia.org
991,"EMERGENCY PHYSICIANS AT PORTER HOSPITALS, PC",Male,Violet,Software Engineer IV,507-66-1765,12/27/1992,Ustupo,Panama,997-607-2718,tsantorirj@redcross.org
992,TOTAL HOSPITAL CARE,Female,Teal,Director of Sales,241-47-5751,5/25/1973,Juatuba,Brazil,196-597-8136,sclutheramrk@businesswire.com
993,PRAIRIE COUNTY HOSPITAL DISTRICT,Female,Goldenrod,Marketing Manager,135-93-3636,9/25/1953,Chusovoy,Russia,163-950-5880,kmanisrl@shareasale.com
994,BRONSON METHODIST HOSPITAL,Female,Purple,Administrative Assistant III,507-70-7626,2/12/1957,Bungoma,Kenya,169-243-5351,psparrowerm@theguardian.com
995,"PROMISE HOSPITAL OF ASCENSION, INC.",Female,Teal,Database Administrator III,721-46-0324,5/6/1988,Mantes-la-Jolie,France,871-485-7072,tfaldoern@unesco.org
996,THE CAMBRIDGE HOSPITAL,Female,Indigo,Executive Secretary,735-52-4327,4/2/1984,Peicheng,China,824-715-0847,aridgerro@prlog.org
997,EAST ORANGE GENERAL HOSPITAL,Male,Orange,Geological Engineer,885-37-7943,11/20/1957,Askainen,Finland,358-151-6573,mlarozerp@hostgator.com
998,SALEM MEMORIAL HOSPITAL,Female,Maroon,Electrical Engineer,157-51-4509,2/29/1996,Līkak,Iran,466-151-5908,nluffmanrq@cargocollective.com
999,MARY IMOGENE BASSETT HOSPITAL,Male,Red,Human Resources Assistant II,880-41-9582,11/16/1953,Niverville,Canada,920-360-2577,mmcgloinrr@ycombinator.com

In [12]:
# getting access to the shape attribute
df_exams.shape

(1000, 10)

In [13]:
# display n rows
pd.set_option('display.max_rows',1000)
df_exams

,hospital_name,gender,color,job_title,ssn,birthdate,city,country,phone_number,email
0,WAGONER HOSPITAL AUTHORITY,Female,Maroon,Social Worker,414-96-9723,9/23/1980,Fraile Pintado,Argentina,644-374-7372,gchansonnau0@live.com
1,ATHOL MEMORIAL HOSPITAL INCORPORATED,Female,Orange,Social Worker,158-68-8337,8/31/1954,Taxisco,Guatemala,487-683-5255,cwinckworth1@about.com
2,MCLEOD REGIONAL MEDICAL CENTER OF PEE DEE INC,Male,Khaki,Quality Engineer,656-97-2511,3/16/1973,Sakai,Japan,255-989-3989,hsollars2@google.com
3,SUTTER VALLEY HOSPITALS,Male,Maroon,Web Developer I,598-01-7806,5/14/1974,Кондово,Macedonia,650-792-4085,ahallward3@theguardian.com
4,NORTH SUNFLOWER MEDICAL CENTER,Male,Pink,Senior Sales Associate,776-58-1786,12/30/1962,Bāfq,Iran,110-479-5503,vkirke4@joomla.org
5,HOLLAND COMMUNITY HOSPITAL,Male,Maroon,Cost Accountant,763-39-0421,10/23/2000,Saint Paul,United States,651-574-7884,ematteacci5@reverbnation.com
6,SHARP MEMORIAL HOSPITAL,Male,Violet,Community Outreach Specialist,528-61-7082,5/31/1995,Bakovci,Slovenia,551-743-1116,bspight6@usda.gov
7,"MEDICAL CENTER PHARMACY AND HOME CARE CENTER, ...",Male,Pink,Tax Accountant,586-85-4755,10/4/1979,Svecha,Russia,137-630-1558,ctester7@google.co.jp
8,"MARGARET MARY COMMUNITY HOSPITAL, INC.",Female,Yellow,Senior Developer,718-63-4266,8/30/1956,Naji,China,143-319-9940,cboswell8@livejournal.com
9,HENRY FORD WYANDOTTE HOSPITAL,Male,Mauv,Assistant Manager,602-40-7016,9/19/1963,Humaitá,Brazil,936-836-8022,ssponder9@japanpost.jp
10,GOOD SAMARITAN HOSPITAL MEDICAL CENTER,Female,Fuscia,Assistant Media Planner,392-64-6676,10/19/1996,Machikou,China,717-631-9238,mobella@cocolog-nifty.com
11,JACKSON HOSPITAL CORPORATION,Female,Goldenrod,Account Executive,291-23-9252,7/1/1998,Rockford,United States,815-789-1834,gcornejob@sohu.com
12,"SOUTHERN MARYLAND HOSPITAL, INC.",Female,Fuscia,Editor,163-17-2840,11/9/1950,Pitogo,Philippines,949-399-5804,jrozeac@timesonline.co.uk
13,SURGICAL HOSPITAL OF AUSTIN,Female,Purple,Safety Technician II,260-77-8524,11/16/1976,Grand Forks,United States,701-617-0720,mcarlucciod@home.pl
14,VIRGINIA GAY HOSPITAL,Female,Fuscia,Assistant Media Planner,513-79-1874,6/5/1972,Cerro Azul,Argentina,157-948-3701,csoutare@reference.com
15,CHILDRENS HOSPITAL OF NY,Female,Mauv,Community Outreach Specialist,726-94-4236,8/4/1994,Zaragoza,Mexico,926-342-5245,acastellonef@mapy.cz
16,CRAWFORD HOSPITAL DISTRICT,Female,Aquamarine,Engineer II,266-50-1987,7/17/1963,Yangxiang,China,783-428-5866,afutcherg@blogger.com
17,"COASTAL MEDICAL CENTER PA C/O PAUL D BRUNS, JR...",Male,Red,Associate Professor,699-22-8292,4/27/1956,Zengtian,China,372-760-6046,cgrundeyh@huffingtonpost.com
18,ORANGE CITY MUNICIPAL HOSPITAL,Genderqueer,Blue,Financial Advisor,268-50-1460,9/27/1950,Omu Aran,Nigeria,945-441-0123,fcormodei@rediff.com
19,MEDSTAR SOUTHERN MARYLAND HOSPITAL CENTER INC,Female,Green,Marketing Assistant,729-03-5061,1/22/1979,Skanör,Sweden,113-977-1811,mdodgej@comsenz.com
20,APEX MEDICAL CENTERS LLC,Female,Goldenrod,Research Nurse,290-72-3372,8/12/1980,Zhoutou,China,950-214-6025,rkarolowskik@icio.us
21,NORTHSIDE HOSPITAL,Female,Aquamarine,GIS Technical Architect,273-12-7584,11/30/1955,Bosanski Šamac,Bosnia and Herzegovina,401-457-5282,tvandalel@unesco.org
22,ST VINCENT HOSPITAL-HOSPITAL SISTERS-THIRD ORD...,Female,Goldenrod,Staff Scientist,803-46-6004,5/25/1981,Sakado,Japan,126-187-0960,jviccarym@yellowpages.com
23,NORTHERN HOSPITAL OF SURRY COUNTY,Female,Maroon,Data Coordinator,371-11-9774,4/12/1959,Bijela,Montenegro,409-215-7520,lbegleyn@nsw.gov.au
24,BANNER -- UNIVERSITY MEDICAL CENTER TUCSON CAM...,Male,Indigo,Nurse,631-03-4790,8/28/1979,Fuwayriţ,Qatar,713-578-3743,lwainscoto@seattletimes.com
25,BRIDGE MEDICAL CENTER PROFESSIONAL ASSOCIATION,Male,Khaki,Nuclear Power Engineer,582-20-0239,5/10/1981,Talovyy,Russia,440-672-2055,dlatorrep@archive.org
26,COMMUNITY MEDICAL CENTER INC,Male,Teal,Teacher,286-67-2564,1/9/1957,Tonggu,China,815-448-2710,browlandsq@whitehouse.gov
27,"BATESVILLE REGIONAL MEDICAL CENTER, INC.",Female,Green,Research Assistant IV,139-48-0639,10/23/1956,San Isidro,Mexico,450-658-2303,bziemensr@abc.net.au
28,FORREST COUNTY GENERAL HOSPITAL,Female,Goldenrod,Computer Systems Analyst IV,392-95-5569,1/7/1968,Atap,Indonesia,459-826-4452,tstouthers@reuters.com
29,ANDREWS CENTER-PARTIAL HOSPITALIZATOIN,Female,Pink,Junior Executive,776-93-5637,7/16/1976,Rassvet,Russia,724-486-0198,abrentont@exblog.jp
30,"DELAWARE VALLEY HOSPITAL, INC.",Male,Violet,Environmental Specialist,792-21-8149,3/8/1966,Chaowai,China,177-601-8749,gclausu@cdc.gov
31,CAMDEN ON GAULEY MEDICAL CENTER INC,Female,Turquoise,Actuary,562-17-4723,9/8/1960,Sancha,China,538-175-9630,nlarratv@cargocollective.com
32,EAST TENNESSEE CHILDREN'S HOSPITAL PRIMARY CAR...,Female,Indigo,Programmer Analyst II,667-38-2272,9/12/1951,Chidian,China,601-387-6006,npellingarw@soundcloud.com
33,AGILENCE ARTHRITIS AND OSTEOPOROSIS MEDICAL CE...,Male,Blue,Research Associate,528-48-0194,2/23/1973,Huixian Chengguanzhen,China,189-394-4918,mcoppenx@unicef.org
34,ELITE HEALTH MEDICAL CENTERS,Female,Fuscia,Computer Systems Analyst I,466-99-0487,12/6/1986,Shidu,China,799-818-3355,apiketty@simplemachines.org
35,SHORE HOSPITALISTS ASSOCIATES PA,Female,Mauv,Project Manager,735-07-7994,2/28/1968,Mikun’,Russia,605-145-6424,mlittlechildz@miibeian.gov.cn
36,BROOKLYN PLAZA MEDICAL CENTER,Female,Teal,Financial Analyst,880-21-5756,6/20/1985,Gandara,Portugal,181-425-2581,aoneill10@alexa.com
37,HOLY CROSS HOSPITAL INC,Female,Puce,Automation Specialist II,720-21-3557,9/28/1984,Shuiyang,China,267-945-3865,ecostard11@cyberchimps.com
38,MONTEFIORE MEDICAL CENTER,Female,Aquamarine,Senior Financial Analyst,644-31-8712,3/11/1979,Cubatão,Brazil,805-444-6095,swilhelmy12@stanford.edu
39,LEGACY EMANUEL HOSPITAL & HEALTH CENTER,Female,Orange,Assistant Manager,318-32-1738,12/31/1951,Suzano,Brazil,814-430-2801,tmclardie13@admin.ch
40,"OUR LADY OF BELLEFONTE HOSPITAL, INC",Agender,Turquoise,Software Engineer III,726-57-3123,10/18/1969,Limit,Jamaica,209-761-4360,mfellow14@youku.com
41,NAVAL MEDICAL CENTER SAN DIEGO,Female,Red,Desktop Support Technician,707-18-7001,8/15/1973,Maicao,Colombia,586-504-9612,hcordeix15@archive.org
42,FIRST CALL MEDICAL CENTER LLC,Female,Indigo,Quality Engineer,254-33-0284,12/1/1962,Samangawah,Indonesia,672-627-0273,arawlcliffe16@shinystat.com
43,JACKSON COUNTY SCHNECK MEMORIAL HOSPITAL,Female,Green,Biostatistician II,764-38-0505,7/19/1978,Dar Chabanne,Tunisia,873-679-4516,cmacdermot17@army.mil
44,CHILDREN'S HOSPITAL COLORADO,Male,Khaki,Mechanical Systems Engineer,141-37-8450,8/19/2001,Oltinko’l,Uzbekistan,937-387-8917,apaviour18@umn.edu
45,EAST TENNESSEE CHILDREN'S HOSPITAL ASSOCIATION...,Male,Khaki,Professor,137-86-5886,1/22/1977,Luba,Equatorial Guinea,662-194-7077,wwelton19@va.gov
46,RWJ BARNABASHEALTH - JERSEY CITY MEDICAL CENTER,Male,Khaki,Computer Systems Analyst III,770-81-0328,7/19/1987,Rybnoye,Russia,829-402-1915,mjanu1a@craigslist.org
47,MERCY HEALTH - TIFFIN HOSPITAL LLC,Agender,Fuscia,Safety Technician III,722-96-2651,12/1/1983,Mosjøen,Norway,544-731-4983,lpinwell1b@webeden.co.uk
48,KNOX COMMUNITY HOSPITAL,Male,Turquoise,Marketing Manager,249-08-3202,11/23/1962,Kananga,Democratic Republic of the Congo,507-598-0976,blesser1c@woothemes.com
49,BARBARA ANN KARMANOS CANCER HOSPITAL,Female,Orange,VP Quality Control,574-35-2455,3/22/1992,Paraíso de Chabasquén,Venezuela,644-519-6001,aohm1d@wikipedia.org
50,HMH HOSPITALS CORPORATION,Male,Maroon,Executive Secretary,205-77-8953,7/27/1995,Peraía,Greece,338-328-1997,gdeville1e@multiply.com
51,SARATOGA HOSPITAL,Female,Fuscia,Nurse Practicioner,680-55-6352,2/4/1962,Starobachaty,Russia,730-801-7610,bantliff1f@cbsnews.com
52,SINAI HOSPITAL OF BALTIMORE INC,Female,Khaki,Accountant III,768-90-8006,1/22/1980,Suqin Huimin,China,917-856-2216,abannon1g@zimbio.com
53,ST FRANCIS HOSPITAL,Female,Fuscia,Assistant Media Planner,608-66-1126,7/30/1972,Jiyang,China,515-228-5133,sarmsby1h@naver.com
54,LOYOLA UNIVERSITY MEDICAL CENTER,Male,Mauv,Environmental Tech,683-09-4177,12/28/1997,Krasnyy Oktyabr’,Russia,856-750-9714,nmcbrier1i@opera.com
55,KENMORE MERCY HOSPITAL,Female,Violet,Operator,453-55-7266,4/21/1967,Kampong Chhnang,Cambodia,997-541-5567,civannikov1j@amazon.co.jp
56,CAMBRIDGE MEDICAL CENTER URGENT CARE,Female,Indigo,Financial Analyst,410-37-9396,6/1/1977,Sarapul,Russia,403-464-6876,mrawlin1k@oracle.com
57,NAVAL MEDICAL CENTER SAN DIEGO,Male,Teal,Database Administrator I,611-28-8269,12/10/1957,Palcamayo,Peru,632-758-5920,cembury1l@ucoz.com
58,SUNNYSIDE COMMUNITY HOSPITAL ASSOCIATION,Female,Goldenrod,Editor,866-36-9797,4/23/1962,Vsevolozhsk,Russia,185-483-7306,griggulsford1m@nasa.gov
59,PULASKI MEMORIAL HOSPITAL,Male,Violet,Computer Systems Analyst I,864-64-4355,9/20/1978,Sanli,China,231-256-2941,crainon1n@dailymail.co.uk
60,DALLAS COUNTY HOSPITAL DISTRICT,Female,Teal,Assistant Professor,333-83-9029,9/20/1977,Jiachuan,China,699-247-3572,jbegwell1o@ycombinator.com
61,"FLORIDA STATE UNIVERSITY, PEDIATRIC RESIDENCY ...",Male,Maroon,Legal Assistant,437-96-4147,4/15/1977,San Antonio,Peru,690-408-2647,cmacguffog1p@jigsy.com
62,MERITUS MEDICAL CENTER INC,Male,Yellow,VP Accounting,580-16-5414,4/2/1988,Rosaspata,Peru,550-381-6465,alebond1q@pagesperso-orange.fr
63,SETON MEDICAL CENTER COATSIDE,Female,Mauv,Desktop Support Technician,357-57-9962,6/15/1968,Tuluá,Colombia,293-158-2714,bvel1r@ca.gov
64,ST LUKE HOSPITAL,Female,Green,VP Quality Control,319-37-4118,3/9/1962,Pleszew,Poland,359-113-2696,fmadocjones1s@apache.org
65,BOARD OF TRUSTEES OF HOWARD COMMUNITY HOSPITAL,Male,Turquoise,Quality Engineer,581-21-0389,3/23/1994,Bariri,Brazil,803-843-4342,lthursby1t@foxnews.com
66,CARLE EUREKA HOSPITAL,Female,Aquamarine,Environmental Tech,506-41-0862,6/19/1953,Bordeaux,France,500-492-6409,tcoghlan1u@jalbum.net
67,"SOUTH CENTRAL HOSPITALISTS, LLP",Male,Orange,Compensation Analyst,568-03-4553,11/6/2000,Sūrīān,Iran,694-486-8143,tswire1v@sitemeter.com
68,"GLENN MEDICAL CENTER, LLC",Female,Violet,Health Coach II,489-97-8322,10/8/1992,Petoa,Honduras,719-777-5563,cjacobsz1w@i2i.jp
69,CONNECTICUT CHILDREN'S MEDICAL CENTER,Male,Crimson,Geologist II,519-87-8515,1/15/1970,Huacaschuque,Peru,778-431-1907,tspellicy1x@cafepress.com
70,MERCY HEALTH-ST RITAS MEDICAL CENTER LLC,Male,Teal,Cost Accountant,550-90-9042,6/22/1981,Ramón Castilla,Peru,269-583-6960,erubinsztein1y@wikipedia.org
71,CITY MEDICAL CENTER INC.,Male,Maroon,Office Assistant II,515-31-4175,3/30/1962,Koz’modem’yansk,Russia,665-782-9449,mkubik1z@yale.edu
72,VIRGINIA HOSPITAL CENTER PHYSICIAN GROUP LLC,Male,Fuscia,Programmer Analyst I,550-75-6266,3/26/1965,Rizómata,Greece,925-145-9195,vduchenne20@latimes.com
73,BENSON AREA MEDICAL CENTER,Female,Mauv,Senior Financial Analyst,707-60-2177,8/19/1993,Araçatuba,Brazil,115-132-1725,pcollidge21@un.org
74,NORTHEAST GEORGIA MEDICAL CENTER INC,Female,Red,Product Engineer,203-36-4794,11/29/1978,Agía Varvára,Greece,354-301-9756,oskuce22@ebay.co.uk
75,"ADVANCED EYE CARE MEDICAL CENTER, PA",Male,Orange,Staff Scientist,707-40-0691,12/18/1956,Podebłocie,Poland,525-524-3495,zvanson23@adobe.com
76,NORTH SHORE UNIVERSITY HEALTHSYSTEMS EVANSTON ...,Female,Maroon,Administrative Assistant I,164-86-8842,12/8/1957,Sigu,China,374-950-3221,awoodhead24@wired.com
77,MURRAY-CALLOWAY COUNTY PUBLIC HOSPITAL CORPORA...,Female,Puce,Developer II,134-39-5156,9/7/1996,Taraban Timur,Indonesia,702-655-8688,jgrieve25@statcounter.com
78,DALLAS COUNTY HOSPITAL DISTRICT,Male,Pink,Developer II,615-34-2844,4/6/1979,Rembes,Indonesia,613-809-3713,jkitteman26@ox.ac.uk
79,LOCKNEY GENERAL HOSPITAL DISTRICT,Female,Puce,Dental Hygienist,867-97-7322,7/15/1955,Changshengqiao,China,886-424-1748,rolynn27@prnewswire.com
80,LESTER E COX MEDICAL CENTERS,Male,Maroon,Pharmacist,674-17-7664,2/18/1968,Bang Pa-in,Thailand,964-770-1571,hcrichley28@utexas.edu
81,THE MIRIAM HOSPITAL,Male,Khaki,Executive Secretary,322-53-5000,7/21/1979,Burgeo,Canada,481-735-8307,tpargetter29@miibeian.gov.cn
82,VIRGINIA MASON MEDICAL CENTER,Male,Blue,VP Marketing,103-14-7856,6/26/1984,Mouquim,Portugal,189-603-8462,mdiaper2a@phpbb.com
83,SPINE AND PAIN TREATMENT MEDICAL CENTER OF SAN...,Male,Khaki,VP Accounting,823-73-9170,2/15/1964,Barueri,Brazil,936-962-4071,mplummer2b@vistaprint.com
84,BINGHAM MEMORIAL HOSPITAL,Male,Crimson,Desktop Support Technician,892-19-9948,8/10/2001,Haiphong,Vietnam,844-117-0558,dvilla2c@illinois.edu
85,MARYVIEW HOSPITAL,Female,Mauv,Staff Scientist,740-17-0126,6/25/1960,Whakatane,New Zealand,932-884-3777,btoretta2d@free.fr
86,PS MEDICAL CENTER INC,Male,Aquamarine,Software Test Engineer IV,791-40-0955,6/17/1950,København,Denmark,574-211-3810,ccamblin2e@gnu.org
87,"ESCAMBIA COUNTY ALABAMA COMMUNITY HOSPITALS, INC.",Male,Puce,Sales Associate,723-86-8815,11/15/1969,Payapa,Philippines,987-572-5769,tyitzovicz2f@wufoo.com
88,HOLY CROSS HOSPITAL,Male,Teal,Human Resources Manager,223-53-2714,11/8/1992,Hudai,China,215-728-8520,msale2g@umn.edu
89,MORROW COUNTY HOSPITAL,Male,Pink,Social Worker,253-68-6744,7/15/1965,Mekarsari,Indonesia,668-964-9465,djankovic2h@discuz.net
90,JERSEY COMMUNITY HOSPITAL,Female,Aquamarine,Internal Auditor,450-33-3185,2/1/1968,Binuangan,Philippines,909-465-9847,npauls2i@uol.com.br
91,COVINGTON COUNTY HOSPITAL,Male,Puce,Registered Nurse,145-42-6624,7/1/1998,Bilhó,Portugal,143-528-5882,abelmont2j@dmoz.org
92,MORTON PLANT HOSPITAL,Male,Violet,Software Consultant,545-98-7999,3/10/1981,Kristiansand S,Norway,211-510-5159,sasee2k@comcast.net
93,PUBLIC HOSPITAL DISTRICT NO 2,Polygender,Puce,Database Administrator III,417-14-3921,4/20/1954,Jinping,China,890-131-6154,jwyrall2l@sogou.com
94,THE MILTON S. HERSHEY MEDICAL CENTER PHYSICIAN...,Male,Maroon,Internal Auditor,823-99-6146,6/23/1986,Raydah,Yemen,331-749-4832,bjohannesson2m@wikipedia.org
95,CHG CORNERSTONE HOSPITAL OF AUSTIN,Female,Teal,Registered Nurse,256-18-7944,6/24/1959,Braga,Portugal,190-109-8942,ccliffe2n@ning.com
96,EAST PENN MEDICAL CENTER,Male,Khaki,Software Engineer III,611-99-1022,8/25/1962,Canga’an,Indonesia,588-253-9912,speyto2o@kickstarter.com
97,THE REGIONAL MEDICAL CENTER OF ORANGEBURG AND ...,Male,Puce,Software Test Engineer I,272-96-2517,5/3/1972,Maramag,Philippines,360-877-0289,tgadsdon2p@dailymotion.com
98,SOUTHSIDE HOSPITAL HHA,Female,Mauv,Technical Writer,367-59-9539,6/10/1957,Qorovulbozor Shahri,Uzbekistan,359-568-2138,fbaike2q@nature.com
99,VARIETY CHILDREN'S HOSPITAL,Non-binary,Crimson,Chief Design Engineer,755-95-4600,4/6/1964,Dār an Naşr,Yemen,890-511-5084,ccomoletti2r@blog.com
100,PRINCETON MEMORIAL HOSPITAL COMPANY,Female,Orange,Design Engineer,610-62-8708,8/13/1963,Vetluzhskiy,Russia,899-757-2375,cbernette2s@reuters.com
101,COMMUNITY MEDICAL CENTER INC,Male,Indigo,Operator,735-44-5321,4/1/1977,Houba,China,578-527-1895,dcicutto2t@gravatar.com
102,"UNIVERSITY OF MARYLAND MEDICAL CENTER, LLC",Male,Mauv,Editor,268-33-4449,11/12/1982,Lianyi,China,387-965-3578,awhitehorn2u@so-net.ne.jp
103,LAKESIDE MEMORIAL HOSPITAL INC.,Male,Pink,Budget/Accounting Analyst II,755-31-0072,4/10/1979,Antigonish,Canada,151-381-0227,mfall2v@cnet.com
104,MERCY HEALTH-ST RITAS MEDICAL CENTER LLC,Male,Mauv,Programmer Analyst I,261-04-5453,4/7/1991,Bangker,Indonesia,603-103-3800,cfulker2w@elegantthemes.com
105,CAROLINA MEDICAL CENTER INC,Female,Khaki,Electrical Engineer,248-92-9550,7/29/1991,Slobodskoy,Russia,191-635-5561,dcockerell2x@exblog.jp
106,ST. JOHN'S REGIONAL MEDICAL CENTER,Female,Green,Actuary,754-29-2582,6/2/2000,Bugana,Nigeria,750-515-1458,vjarlmann2y@pcworld.com
107,DIVINE MEDICAL CENTER P C,Male,Mauv,Graphic Designer,484-76-1360,11/19/1952,Chak,Pakistan,689-666-1237,tupton2z@nsw.gov.au
108,"ALPERT MEDICAL CENTER,PC",Genderfluid,Purple,Marketing Assistant,623-07-5559,5/29/1962,Niort,France,825-175-4410,mwhild30@illinois.edu
109,VETERANS MEMORIAL HOSPITAL CITY OF WAUKON IA,Female,Goldenrod,Quality Control Specialist,292-04-5616,9/21/1964,Yangshufang,China,448-767-7374,ehutfield31@163.com
110,HACKLEY HOSPITAL FISCAL SERVICES,Male,Maroon,Civil Engineer,643-48-1412,12/20/2000,Fuxing,China,196-404-9146,jminichi32@un.org
111,"OUR LADY OF THE ANGELS HOSPITAL, INC.",Genderfluid,Blue,Nuclear Power Engineer,849-77-5374,4/27/1981,Guanay,Bolivia,576-999-2594,ddik33@mit.edu
112,HELEN NEWBERRY JOY HOSPITAL,Male,Goldenrod,Speech Pathologist,439-33-8513,4/17/1959,Guanshan,China,262-937-9179,nvousden34@photobucket.com
113,CLAY COUNTY MEDICAL CENTER,Male,Red,Editor,197-22-6091,12/1/1969,Cilangkap,Indonesia,361-917-3590,jlambertciorwyn35@columbia.edu
114,SOUTH LIMESTONE HOSPITAL DISTRICT,Male,Orange,Analog Circuit Design manager,484-57-7342,8/4/1982,Toulouse,France,639-601-5775,smclean36@sun.com
115,GUADALUPE COUNTY HOSPITAL BOARD,Female,Khaki,Physical Therapy Assistant,854-16-1136,6/15/1973,Esfarāyen,Iran,579-534-6669,bbillany37@nyu.edu
116,ENUMCLAW REGIONAL HOSPITAL ASSOCIATION,Male,Turquoise,Sales Representative,547-48-3956,7/22/1959,Papeete,French Polynesia,290-550-5126,dbestwick38@jigsy.com
117,GREENWICH HOSPITAL,Polygender,Indigo,Help Desk Technician,468-13-0572,9/8/1975,Jangas,Peru,970-853-6057,mbellow39@hubpages.com
118,BRAXTON COUNTY MEMORIAL HOSPITAL,Agender,Puce,Human Resources Assistant II,514-06-1381,3/30/1987,Fucheng,China,249-228-9071,talwen3a@google.co.uk
119,SWEDISHAMERICAN HOSPITAL,Male,Fuscia,Structural Analysis Engineer,404-53-0180,1/21/1996,Depok,Indonesia,779-676-3018,bcave3b@blogger.com
120,MEMORIAL HOSPITAL AT GULFPORT,Female,Green,Geologist IV,410-11-6151,12/15/1961,Mirocin,Poland,392-614-0203,hwoodroofe3c@blogspot.com
121,HANNIBAL REGIONAL HOSPITAL,Male,Khaki,Quality Engineer,508-46-9395,6/4/1998,Lincheng,China,923-883-8658,dorowane3d@sbwire.com
122,MOUNT SINAI HOSPITAL,Female,Mauv,GIS Technical Architect,188-51-7431,1/29/1966,Hilversum,Netherlands,611-991-0158,vwarrier3e@ed.gov
123,ST. VINCENT HOSPITAL-HOSPITAL SISTERS-THIRD OR...,Female,Green,Mechanical Systems Engineer,467-37-3030,1/19/1953,Novokuz’minki,Russia,379-398-2638,jsabathier3f@bbc.co.uk
124,"WINDHAM COMMUNITY MEMORIAL HOSPITAL, INC.",Female,Aquamarine,Structural Analysis Engineer,702-79-1411,3/2/1973,Tabu,Philippines,875-464-0214,gjorgensen3g@nationalgeographic.com
125,"INDIGO HOSPITAL MEDICINE - PETOSKEY, PLC",Male,Aquamarine,Actuary,303-19-5252,6/8/1952,Lavadorinhos,Portugal,294-923-6792,gmaccrossan3h@desdev.cn
126,SOUTH LIMESTONE HOSPITAL DISTRICT,Female,Turquoise,Senior Editor,441-67-0115,4/19/1952,Songshan,China,844-858-0729,sgibbins3i@github.io
127,"TRIGG COUNTY HOSPITAL, INC",Male,Red,Clinical Specialist,838-93-1728,4/9/2000,Negla,Indonesia,652-912-6864,gmcdonnell3j@soup.io
128,BATON ROUGE GENERAL MEDICAL CENTER,Male,Khaki,Desktop Support Technician,522-15-0796,9/25/1990,Maesan,Indonesia,613-827-2736,kschiesterl3k@wufoo.com
129,PAM SPECIALTY HOSPITAL OF ROCKY MOUNT LLC,Non-binary,Indigo,Senior Financial Analyst,607-67-2812,11/22/1971,Ban Houakhoua,Laos,928-359-2417,mallflatt3l@globo.com
130,PHOEBE PUTNEY MEMORIAL HOSPITAL,Female,Blue,VP Sales,650-80-5111,10/3/1957,Badong,Indonesia,677-118-0194,cstithe3m@com.com
131,JACOBI MEDICAL CENTER,Female,Purple,Quality Control Specialist,611-35-4213,5/25/1984,Talangbetutu,Indonesia,661-569-8576,correll3n@soundcloud.com
132,VARIETY CHILDREN'S HOSPITAL,Male,Teal,VP Product Management,564-46-4826,12/16/1962,Samdo,China,892-377-7231,bwoloschinski3o@nationalgeographic.com
133,LLANO COUNTY HOSPITAL AUTHORITY,Female,Blue,Research Assistant I,832-36-0142,2/28/1983,Xinshui,China,505-671-8243,kselbach3p@ifeng.com
134,NY PRESBYTERIAN HOSPITAL - CORNELL,Female,Goldenrod,Clinical Specialist,514-57-4183,6/26/2000,Karlskrona,Sweden,877-658-8303,apendell3q@opensource.org
135,COLUMBIA UNIVERSITY MEDICAL CENTER,Male,Violet,Senior Quality Engineer,595-23-7214,9/5/1963,Suklayin,Philippines,658-682-6754,kstringman3r@ocn.ne.jp
136,ST. FRANCIS HOSPITAL AND HEALTH CENTERS,Female,Mauv,Accounting Assistant IV,728-44-5318,8/21/1971,Lubbock,United States,806-427-4220,iletty3s@psu.edu