In [1]:
import pandas as pd

In [2]:
# reading the csv file
df_exams = pd.read_csv(r"C:\Users\krishna rawal\dataset.csv")
df_exams.head()

,hospital_name,gender,color,job_title,ssn,birthdate,city,country,phone_number,email
0,WAGONER HOSPITAL AUTHORITY,Female,Maroon,Social Worker,414-96-9723,9/23/1980,Fraile Pintado,Argentina,644-374-7372,gchansonnau0@live.com
1,ATHOL MEMORIAL HOSPITAL INCORPORATED,Female,Orange,Social Worker,158-68-8337,8/31/1954,Taxisco,Guatemala,487-683-5255,cwinckworth1@about.com
2,MCLEOD REGIONAL MEDICAL CENTER OF PEE DEE INC,Male,Khaki,Quality Engineer,656-97-2511,3/16/1973,Sakai,Japan,255-989-3989,hsollars2@google.com
3,SUTTER VALLEY HOSPITALS,Male,Maroon,Web Developer I,598-01-7806,5/14/1974,Кондово,Macedonia,650-792-4085,ahallward3@theguardian.com
4,NORTH SUNFLOWER MEDICAL CENTER,Male,Pink,Senior Sales Associate,776-58-1786,12/30/1962,Bāfq,Iran,110-479-5503,vkirke4@joomla.org

## Selcting two or more columns

In [3]:
# select 2 columns using[[]]
df_exams[['gender','color']]
# two pairs of [[]] ---> dataframe
# one pair of [] ---> series

     gender   color
0    Female  Maroon
1    Female  Orange
2      Male   Khaki
3      Male  Maroon
4      Male    Pink
..      ...     ...
995  Female    Teal
996  Female  Indigo
997    Male  Orange
998  Female  Maroon
999    Male     Red

[1000 rows x 2 columns]

In [4]:
# checkout the data type of the selection
type(df_exams[['gender','color']])

pandas.DataFrame

In [6]:
# select two or more columns using [[]]
df_exams[['gender','color','ssn','city']]

     gender   color          ssn             city
0    Female  Maroon  414-96-9723   Fraile Pintado
1    Female  Orange  158-68-8337          Taxisco
2      Male   Khaki  656-97-2511            Sakai
3      Male  Maroon  598-01-7806          Кондово
4      Male    Pink  776-58-1786             Bāfq
..      ...     ...          ...              ...
995  Female    Teal  721-46-0324  Mantes-la-Jolie
996  Female  Indigo  735-52-4327         Peicheng
997    Male  Orange  885-37-7943         Askainen
998  Female  Maroon  157-51-4509            Līkak
999    Male     Red  880-41-9582       Niverville

[1000 rows x 4 columns]

In [7]:
# advantage of [] over '.' 
# we cant select two or more columns with '.'
df_exams.'gender','city'

SyntaxError: invalid syntax (1133737211.py, line 3)