In [1]:
import pandas as pd

In [2]:
# reading the csv file
df_exams = pd.read_csv(r"C:\Users\krishna rawal\dataset.csv")
df_exams.head()

,hospital_name,gender,color,job_title,ssn,birthdate,city,country,phone_number,email
0,WAGONER HOSPITAL AUTHORITY,Female,Maroon,Social Worker,414-96-9723,9/23/1980,Fraile Pintado,Argentina,644-374-7372,gchansonnau0@live.com
1,ATHOL MEMORIAL HOSPITAL INCORPORATED,Female,Orange,Social Worker,158-68-8337,8/31/1954,Taxisco,Guatemala,487-683-5255,cwinckworth1@about.com
2,MCLEOD REGIONAL MEDICAL CENTER OF PEE DEE INC,Male,Khaki,Quality Engineer,656-97-2511,3/16/1973,Sakai,Japan,255-989-3989,hsollars2@google.com
3,SUTTER VALLEY HOSPITALS,Male,Maroon,Web Developer I,598-01-7806,5/14/1974,Кондово,Macedonia,650-792-4085,ahallward3@theguardian.com
4,NORTH SUNFLOWER MEDICAL CENTER,Male,Pink,Senior Sales Associate,776-58-1786,12/30/1962,Bāfq,Iran,110-479-5503,vkirke4@joomla.org

## 1.Adding a new column

### 1.1 Adding a new column with a scalar value

In [5]:
# Adding a new column to a dataframe
df_exams['language'] = "Hindi"
df_exams

,hospital_name,gender,color,job_title,ssn,birthdate,city,country,phone_number,email,language
0,WAGONER HOSPITAL AUTHORITY,Female,Maroon,Social Worker,414-96-9723,9/23/1980,Fraile Pintado,Argentina,644-374-7372,gchansonnau0@live.com,Hindi
1,ATHOL MEMORIAL HOSPITAL INCORPORATED,Female,Orange,Social Worker,158-68-8337,8/31/1954,Taxisco,Guatemala,487-683-5255,cwinckworth1@about.com,Hindi
2,MCLEOD REGIONAL MEDICAL CENTER OF PEE DEE INC,Male,Khaki,Quality Engineer,656-97-2511,3/16/1973,Sakai,Japan,255-989-3989,hsollars2@google.com,Hindi
3,SUTTER VALLEY HOSPITALS,Male,Maroon,Web Developer I,598-01-7806,5/14/1974,Кондово,Macedonia,650-792-4085,ahallward3@theguardian.com,Hindi
4,NORTH SUNFLOWER MEDICAL CENTER,Male,Pink,Senior Sales Associate,776-58-1786,12/30/1962,Bāfq,Iran,110-479-5503,vkirke4@joomla.org,Hindi
...,...,...,...,...,...,...,...,...,...,...,...
995,"PROMISE HOSPITAL OF ASCENSION, INC.",Female,Teal,Database Administrator III,721-46-0324,5/6/1988,Mantes-la-Jolie,France,871-485-7072,tfaldoern@unesco.org,Hindi
996,THE CAMBRIDGE HOSPITAL,Female,Indigo,Executive Secretary,735-52-4327,4/2/1984,Peicheng,China,824-715-0847,aridgerro@prlog.org,Hindi
997,EAST ORANGE GENERAL HOSPITAL,Male,Orange,Geological Engineer,885-37-7943,11/20/1957,Askainen,Finland,358-151-6573,mlarozerp@hostgator.com,Hindi
998,SALEM MEMORIAL HOSPITAL,Female,Maroon,Electrical Engineer,157-51-4509,2/29/1996,Līkak,Iran,466-151-5908,nluffmanrq@cargocollective.com,Hindi
999,MARY IMOGENE BASSETT HOSPITAL,Male,Red,Human Resources Assistant II,880-41-9582,11/16/1953,Niverville,Canada,920-360-2577,mmcgloinrr@ycombinator.com,Hindi

## 1.2 Adding a new column with an array

#### The dataframe has 1000 rows , so we need to create an array with 1000 elements

In [6]:
# import numpy
import numpy as np

In [18]:
# Create an array of 1000 element
lan_guage=np.arange(0,1000)
len(lan_guage)

1000

In [20]:
# adding a new column to dataframe with an array
df_exams['language'] = lan_guage
df_exams

,hospital_name,gender,color,job_title,ssn,birthdate,city,country,phone_number,email,language
0,WAGONER HOSPITAL AUTHORITY,Female,Maroon,Social Worker,414-96-9723,9/23/1980,Fraile Pintado,Argentina,644-374-7372,gchansonnau0@live.com,0
1,ATHOL MEMORIAL HOSPITAL INCORPORATED,Female,Orange,Social Worker,158-68-8337,8/31/1954,Taxisco,Guatemala,487-683-5255,cwinckworth1@about.com,1
2,MCLEOD REGIONAL MEDICAL CENTER OF PEE DEE INC,Male,Khaki,Quality Engineer,656-97-2511,3/16/1973,Sakai,Japan,255-989-3989,hsollars2@google.com,2
3,SUTTER VALLEY HOSPITALS,Male,Maroon,Web Developer I,598-01-7806,5/14/1974,Кондово,Macedonia,650-792-4085,ahallward3@theguardian.com,3
4,NORTH SUNFLOWER MEDICAL CENTER,Male,Pink,Senior Sales Associate,776-58-1786,12/30/1962,Bāfq,Iran,110-479-5503,vkirke4@joomla.org,4
...,...,...,...,...,...,...,...,...,...,...,...
995,"PROMISE HOSPITAL OF ASCENSION, INC.",Female,Teal,Database Administrator III,721-46-0324,5/6/1988,Mantes-la-Jolie,France,871-485-7072,tfaldoern@unesco.org,995
996,THE CAMBRIDGE HOSPITAL,Female,Indigo,Executive Secretary,735-52-4327,4/2/1984,Peicheng,China,824-715-0847,aridgerro@prlog.org,996
997,EAST ORANGE GENERAL HOSPITAL,Male,Orange,Geological Engineer,885-37-7943,11/20/1957,Askainen,Finland,358-151-6573,mlarozerp@hostgator.com,997
998,SALEM MEMORIAL HOSPITAL,Female,Maroon,Electrical Engineer,157-51-4509,2/29/1996,Līkak,Iran,466-151-5908,nluffmanrq@cargocollective.com,998
999,MARY IMOGENE BASSETT HOSPITAL,Male,Red,Human Resources Assistant II,880-41-9582,11/16/1953,Niverville,Canada,920-360-2577,mmcgloinrr@ycombinator.com,999

In [23]:
# create random integer numbers between 1 and 100
int_lang_score=np.random.randint(1,100, size=1000)
int_lang_score

array([99, 90, 93, 94, 37, 10, 93, 15, 99, 15, 59, 43, 17, 40, 18, 41, 38,
       90, 34,  5, 49, 76, 62, 47, 74, 45, 91,  5, 37, 62,  4, 50, 39, 21,
       75, 26, 88, 21,  5,  6, 65, 37, 12, 63, 55, 68, 21, 31, 46,  1, 20,
       94, 50, 90, 73, 65, 38, 74, 90,  9, 40, 24, 20, 36, 28, 20, 95, 55,
       24, 19, 83, 37, 19, 27, 86, 51, 89, 15, 66, 40, 45, 62,  8, 96, 78,
       31,  4, 93,  3, 15, 23, 71, 44, 36,  1,  7, 77,  4, 10, 28, 94,  5,
       97, 69, 77, 90, 89, 41, 58, 64,  8, 52, 48, 36,  9, 99, 32, 55, 15,
       43, 53,  4, 37, 98, 37, 87, 36, 94, 81, 14, 48, 47, 47, 32, 59, 39,
       52, 11, 39, 36, 62, 28, 55, 81, 75, 29, 82,  5, 41, 19, 33, 10, 55,
       20, 15,  4, 56, 12, 35, 34, 36, 57, 93, 10, 77, 50, 73, 49, 96, 72,
       50, 98, 19, 42, 86, 75, 67, 78, 11, 94, 96, 37, 56, 56, 83, 88, 62,
       63, 57, 43, 98, 46, 81, 18, 92, 29, 80, 18, 62, 25, 45, 23, 44, 43,
       30, 64, 44, 46, 95, 93, 19, 53, 95,  8, 13, 23, 39, 62, 48, 95, 56,
       21, 55, 89, 57, 11, 41, 64, 91, 11, 49, 75, 20, 53, 79, 55, 42, 84,
       73, 90, 69, 64, 51, 53, 93, 18, 71, 15, 26, 77, 30, 64, 82, 85, 98,
       83, 95, 12,  3, 27, 50, 44, 73,  6, 47, 93,  3, 59, 67, 86, 34, 58,
       94, 29, 23, 12, 26, 49, 44, 58, 47, 26, 20, 18, 23, 69, 18, 98, 51,
       49, 30, 76, 60, 12, 77, 86, 99, 97, 77, 46, 89, 60, 77, 35, 23, 81,
       10,  7, 37,  4, 69, 59, 53,  3, 88, 71, 33, 49, 74, 85, 86, 19, 92,
       15, 78, 13, 90, 65, 41, 27, 41, 48, 20, 43, 29, 77, 39, 82, 24, 65,
        3, 79, 36, 42, 63,  4, 80, 63, 54,  7, 17, 60, 26, 45,  5, 13, 38,
        8, 91, 18, 30, 37, 30, 86, 35, 44, 43, 64, 59, 56,  6, 97, 36, 51,
        9, 71, 38, 99, 39, 67, 98, 29, 75, 49, 70,  6, 36, 37,  3, 99, 78,
       71, 98, 76, 40, 45, 20, 93, 53, 33, 80, 95,  6, 56, 48, 31, 30, 70,
       37, 71, 31, 16, 73, 46, 30,  3, 89, 25, 19, 85, 41, 91, 90, 63, 73,
       20, 99, 52, 39, 62, 54, 38, 78, 47, 13, 93, 41, 40, 77, 32, 19, 61,
       95, 53, 47, 95, 16, 29, 17,  6, 23, 33, 46, 19, 11, 69, 34, 65, 27,
       73, 51, 35, 80, 93,  4, 38, 27, 10, 44, 67, 72, 47, 90, 11, 92, 27,
       34, 34, 98, 49, 67,  8, 12, 96, 68, 16, 38, 69, 77, 88, 94, 46, 17,
       19, 12, 58, 99, 53, 30, 72,  7, 93, 17, 29, 29, 63, 92, 78, 76, 70,
       68, 62, 13, 71, 48, 93,  2, 86, 17, 43, 84, 21, 74, 10, 34, 14, 31,
       59, 33, 27, 64, 69, 95,  3, 76, 64, 88, 95, 47, 77,  1, 80, 43, 61,
       60, 95, 23, 82,  2, 58, 56, 58, 90, 36, 52, 38, 94, 12, 69, 31, 39,
       42, 96, 72, 36, 86, 26,  7, 86, 10, 64, 29, 74, 17, 65, 47,  5, 34,
       22, 60,  3, 54,  1, 10, 65, 27, 72, 78, 56, 84,  8, 46, 97,  9, 28,
       73, 57, 19, 43,  7, 90, 40, 48, 14, 18, 23, 39, 85, 66, 32, 91, 30,
       73, 13, 94, 95, 88,  4, 24, 17, 40, 65, 83, 97, 64, 61, 73, 43,  1,
       36,  7,  2, 63, 42, 15, 70, 68, 79, 99,  2, 27, 72, 74,  2, 81, 36,
       37, 86, 14, 63, 54, 14, 18, 89, 52, 37, 20, 44,  1,  1, 29, 31, 87,
       36, 99, 71, 32, 45, 57, 40, 11, 26, 61, 32, 54, 56, 78, 22, 11, 93,
       46, 89, 72, 56, 10, 41, 65,  8,  8, 50, 21, 72, 34, 18,  2, 20, 47,
       28, 53,  8, 34, 62, 70, 34,  6,  1, 25, 90, 71, 44, 84, 79, 42, 29,
       42, 66, 75, 55, 80, 10, 72, 65,  4,  7, 93, 68, 29, 16, 70, 44, 56,
       11, 56, 50, 80, 69, 36, 19, 29, 74,  2,  9, 41, 83, 21, 90, 36, 76,
       61, 92, 78, 22, 32, 62, 32, 36, 55, 50, 94, 86,  5, 38, 72,  4, 77,
       88, 76, 13,  2, 43, 81, 70, 92, 87, 57, 35, 29, 16, 26, 96, 76, 12,
        1, 17, 92, 73, 10, 20, 15,  7,  6, 44, 65, 76, 53, 54, 44, 23, 62,
       35, 17, 92, 51,  9,  1, 14, 42, 47, 74,  2, 63,  5, 28, 67, 91, 98,
       39,  6, 56, 21, 74, 96, 72, 42, 78, 12, 85, 87, 61, 23,  8, 17, 25,
       17, 83, 42, 91, 14, 86, 52,  3, 35, 36, 34, 18, 92, 75, 43, 97, 97,
       88, 15, 37,  1, 99, 78, 37, 17, 24, 12, 55, 81, 21, 60, 49, 16, 87,
       99,  5, 17, 59, 12, 38, 88, 31, 86, 24, 43, 39, 74, 76, 80, 42, 54,
       33, 79, 82, 86, 82, 39, 60, 70,  6, 87, 35, 75, 21, 86, 11, 57, 93,
       18,  3, 45, 51, 66, 15,  3, 86, 60, 32, 93, 93, 51, 95, 85, 29, 54,
       65, 72, 82, 70, 80, 87, 76, 19, 90, 41, 49, 75, 33, 53, 13, 77, 53,
       53, 30,  2,  1, 72,  1, 69, 89, 96, 45, 94, 51, 54, 68, 82, 63, 26,
       92, 42, 95, 72, 90, 96,  9, 92, 75, 76,  2, 69, 62, 96, 98, 66, 75,
       45, 79, 42, 26,  7, 39, 20, 76, 34, 16,  5, 95, 26, 81, 68, 96, 49,
       98, 77, 50, 75, 33, 99,  8,  7, 77,  6, 41, 63, 17, 36],
      dtype=int32)

In [25]:
# min value inclusive and high value exclusive
min(int_lang_score)
max(int_lang_score)

np.int32(99)

In [26]:
#adding a new column to dataframe with an array
df_exams['language'] = int_lang_score
df_exams

,hospital_name,gender,color,job_title,ssn,birthdate,city,country,phone_number,email,language
0,WAGONER HOSPITAL AUTHORITY,Female,Maroon,Social Worker,414-96-9723,9/23/1980,Fraile Pintado,Argentina,644-374-7372,gchansonnau0@live.com,99
1,ATHOL MEMORIAL HOSPITAL INCORPORATED,Female,Orange,Social Worker,158-68-8337,8/31/1954,Taxisco,Guatemala,487-683-5255,cwinckworth1@about.com,90
2,MCLEOD REGIONAL MEDICAL CENTER OF PEE DEE INC,Male,Khaki,Quality Engineer,656-97-2511,3/16/1973,Sakai,Japan,255-989-3989,hsollars2@google.com,93
3,SUTTER VALLEY HOSPITALS,Male,Maroon,Web Developer I,598-01-7806,5/14/1974,Кондово,Macedonia,650-792-4085,ahallward3@theguardian.com,94
4,NORTH SUNFLOWER MEDICAL CENTER,Male,Pink,Senior Sales Associate,776-58-1786,12/30/1962,Bāfq,Iran,110-479-5503,vkirke4@joomla.org,37
...,...,...,...,...,...,...,...,...,...,...,...
995,"PROMISE HOSPITAL OF ASCENSION, INC.",Female,Teal,Database Administrator III,721-46-0324,5/6/1988,Mantes-la-Jolie,France,871-485-7072,tfaldoern@unesco.org,6
996,THE CAMBRIDGE HOSPITAL,Female,Indigo,Executive Secretary,735-52-4327,4/2/1984,Peicheng,China,824-715-0847,aridgerro@prlog.org,41
997,EAST ORANGE GENERAL HOSPITAL,Male,Orange,Geological Engineer,885-37-7943,11/20/1957,Askainen,Finland,358-151-6573,mlarozerp@hostgator.com,63
998,SALEM MEMORIAL HOSPITAL,Female,Maroon,Electrical Engineer,157-51-4509,2/29/1996,Līkak,Iran,466-151-5908,nluffmanrq@cargocollective.com,17
999,MARY IMOGENE BASSETT HOSPITAL,Male,Red,Human Resources Assistant II,880-41-9582,11/16/1953,Niverville,Canada,920-360-2577,mmcgloinrr@ycombinator.com,36

In [30]:
# create random float numbers between 1 and 100
np.random.uniform(1,100,size=100)

array([60.74631596, 10.91974593,  3.96828842, 19.11937782, 18.20570521,
       27.6761685 , 45.76831449, 46.55094922, 97.27249519, 97.40963118,
       62.13174148, 55.15698953, 55.05371308, 72.22321926, 49.17769548,
       34.62152305, 92.00545589, 69.75007793, 37.32720512, 30.03565201,
       12.97997234, 40.94048461, 29.04339823, 42.61585963, 99.54540613,
       70.09189743, 15.19127486, 21.87398942,  6.82228463, 68.01140461,
        8.75623268,  8.94503451, 80.57034266, 75.92116485, 98.90579184,
       10.79987474, 17.06743977, 97.52165771, 34.79424368, 32.03168254,
       17.36332088, 59.32361724,  6.88477073,  9.83277054, 62.63070612,
       19.40724807, 27.54995047, 32.65790255, 28.14139869, 20.0707692 ,
       36.60382466, 84.51255096, 17.12384716, 46.87231927, 87.76619926,
       43.8545021 , 65.41791894, 68.86509151, 16.65799123, 16.39922655,
       32.35525606, 78.19107101, 88.30031004, 60.16633646,  4.15485081,
       52.02598977, 35.48987015, 22.6264809 , 36.98524717, 83.50594563,
       19.48823868, 68.88762264, 82.85382542, 12.61635124, 16.15131727,
       69.05695046,  9.99105906, 78.41655631, 68.16994919, 34.34022007,
       69.46873483, 23.12490663, 59.87040484, 66.59802971,  8.88263472,
       97.28561608, 86.59353337, 94.25077285, 40.83625126,  1.49118281,
       11.70114257, 79.91103309, 90.50551907, 22.94763844, 42.65893384,
       39.05205275, 57.08456137,  1.60467793,  3.74900069, 12.76713013])